apiVersion: v1
kind: ConfigMap
metadata:
  name: tasklistenerconfig
data:
  QUEUE_NAME: 'task_changes'
  RABBITMQ_HOST: 'rabbitmq.default.svc.cluster.local'
  PG_LISTEN_CHANNEL: 'data_changes'
  POSTGRES_URL: 'jdbc:postgresql://taskpostgres.default.svc.cluster.local:5432/task'
  RABBITMQ_USERNAME: 'rabbitmq'
  RABBITMQ_PASSWORD: 'rabbitmq'
  METRICS_PORT: "8086"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasklistener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasklistener
  template:
    metadata:
      labels:
        app: tasklistener
    spec:
      containers:
        - name: tasklistener
          image: almer8/postgreslistener
          envFrom:
            - configMapRef:
                name: tasklistenerconfig
          ports:
            - containerPort: 8086

---
apiVersion: v1
kind: Service
metadata:
  name: tasklistener
spec:
  selector:
    app: tasklistener
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  clusterIP: None
---
