apiVersion: v1
kind: ConfigMap
metadata:
  name: sqlite-config
data:
  QUEUE_NAME: 'task_changes'
  RABBITMQ_HOST: 'rabbitmq.default.svc.cluster.local'
  RABBITMQ_USERNAME: 'rabbitmq'
  RABBITMQ_PASSWORD: 'rabbitmq'
  SQLITE_URLS: '["/db/task.db"]'
  METRICS_PORT: "8088"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmigration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmigration
  template:
    metadata:
      labels:
        app: taskmigration
    spec:
      containers:
        - name: taskmigration
          image: almer8/taskmigration
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: sqlite-config
          volumeMounts:
            - name: taskmigration-volume
              mountPath: /db
          ports:
            - containerPort: 8088
      volumes:
        - name: taskmigration-volume
          persistentVolumeClaim:
            claimName: taskmigration-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: taskmigration
spec:
  selector:
    app: taskmigration
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: taskmigration-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/almerlinux/Microservices/db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taskmigration-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
